ParkingBD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     path('admin/', admin.site.urls),
     path('', include('parkingApp.urls')),
     path('user/', include('users.urls')),
     path('bkash/', include('bkash.urls')),

     # path('verification/', include('verify_email.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bkash/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<id>/',views.bkashHome, name='bkashHome' ),
    path('number',views.bkashNumber, name='number' ),
    path('pin/<id>',views.bkashPIN, name='pin' ),
    path('success/<id>',views.bkashSuccess, name='bkashSuccess' ),
]

parkingApp/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile
from PIL import Image
import datetime
from django.core.validators import MaxValueValidator
# from django.conf import settings
# User = settings.AUTH_USER_MODEL

# import geocoder

# Create your models here.

class Division(models.Model):
    division_name = models.CharField(max_length=50)

    def __str__(self):
        return self.division_name


class Locality(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE)

    locality_name = models.CharField(max_length=100)
    post_code = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.locality_name


class PostalCode(models.Model):
    post_code = models.IntegerField()
    neighbouring_area = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.post_code)


class Garage(models.Model):
    locality = models.ForeignKey(Locality, on_delete=models.CASCADE, related_name='garage')
    garage_name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15, blank=False)
    other_number = models.CharField(max_length=15, blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='garage')
    description = models.CharField(max_length=500, blank=False, default='No description')
    photo = models.ImageField(upload_to='garage_photos', blank=False)
    PLACE_CATEGORY_CHOICE = (
        ("Commercial", "Commercial"),
        ("Residential", "Residential"),
    )
    place_category = models.CharField(max_length=20, choices=PLACE_CATEGORY_CHOICE, default="Commercial")
    bike_slot = models.IntegerField(default=0)
    car_slot = models.IntegerField(default=0)
    bicycle_slot = models.IntegerField(default=0)
    allow_monthly = models.BooleanField(default=True)
    monthly_cost = models.FloatField(default=0)
    allow_hourly = models.BooleanField(default=True)
    hourly_cost = models.FloatField(default=0)
    allow_daily = models.BooleanField(default=True)
    daily_cost = models.FloatField(default=0) 
    opening_time = models.TimeField()
    close_time = models.TimeField()
    CCTV = models.BooleanField(default=False)
    Gaurd = models.BooleanField(default=False)
    Indoor = models.BooleanField(default=False)

    location = models.CharField(max_length=100)
    lat = models.FloatField(blank=True, null=True)
    lng = models.FloatField(blank=True, null=True)

    time = datetime.datetime.now()
    
    rating = models.IntegerField(default=0)
    ratingCount = models.IntegerField(default=0)
    avgRating = models.FloatField(default=0)

    postalCode = models.ForeignKey(PostalCode, on_delete=models.CASCADE, default=1)


    def save(self,*args, **kwargs): 
        super().save(*args, **kwargs)
        img = Image.open(self.photo.path)
        if img.height < img.width :
            img.rotate(90)
        if img.height > 480 or img.width > 640 or img.height < 480 or img.width < 640:
            output_size = (480 , 640)
            img.thumbnail(output_size)
            img.save(self.photo.path)

    def __str__(self):
        return self.garage_name


class Booking(models.Model):
    garage = models.ForeignKey(Garage, on_delete=models.CASCADE, related_name='booking')    
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booking_owner')
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='booking_customer')

    customer_address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=20)
    vehice_number = models.CharField(max_length=50)
    VEHICLE_TYPE_CHOICE = (("Bike", "Bike"), ("Car", "Car"), ("Bicycle", "Bicycle"))
    vehicle_type = models.CharField(max_length=20, choices=VEHICLE_TYPE_CHOICE, default="Car")
    image_of_necesssary_papers = models.ImageField(upload_to='Booking_document', blank=True, null=True)
    
    status = models.IntegerField(default=0) 
    #[ 0 = pending, 1 = accepted, 2 = rejected, 3 = completed, 4 = cancelled, 5 = paymentPending, 6 = paymentCompleted, 7 = reviewCompleted]

    BOOKING_TYPE_CHOICE = (
        ("Hour", "Hour"),
        ("Day", "Day"),
        ("Month", "Month"),
    )
    type_of_booking = models.CharField(max_length=20, choices=BOOKING_TYPE_CHOICE, default="Hour")
    booking_quantity = models.IntegerField(default=1)
    start_time = models.CharField(max_length=25)
    start_date = models.CharField(max_length=25)	
    time = models.DateTimeField(auto_now_add=True)

    totalAmount = models.FloatField(default=0)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.garage.garage_name


class CustomerReview(models.Model):
    garage = models.ForeignKey(Garage, on_delete=models.CASCADE, related_name='review')
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='review_customer')
    review = models.CharField(max_length=500, blank=True, null=True)
    # MIN_INT = 0
    # MAX_INT = 5
    # rating = models.IntegerField(default=0)
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.garage.garage_name + "|" + self.customer.username

templates/ParkingBD/GmapSearch.html
{% extends 'ParkingBD/base.html' %}
{% block title %}
Google Map
{% endblock title %}
{% block base %}
<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBm0bpe_luPll4jHCgBgTsuOHI06eikwGA"></script>
<script type="text/javascript">
    navigator.geolocation.getCurrentPosition(success, failure);
    function success(position) {
        var myLat = position.coords.latitude;
        var myLong = position.coords.longitude;
        var coords = new google.maps.LatLng(myLat, myLong);
        var mapOptions = {
            center: coords,
            zoom: 14,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map"), mapOptions);
        var marker = new google.maps.Marker({
            position: coords,
            map: map,
        });

        const popupcontent = new google.maps.InfoWindow({
                    content: "You are here!"
                });
                google.maps.event.addListener(marker, "click", (function (m) {
                    return function () {popupcontent.open(map, m);}
                })(marker));
                document.getElementById('lat').innerHTML = myLat;
                document.getElementById('long').innerHTML = myLong;
    }
    function failure() {
        alert("Sorry, your browser does not support geolocation services.");
    }
</script>

<div>
    <p class="text-center font-semibold text-2xl text-blue-500 m-4">Find parkings around your place</p>
    <div id="map" style="height: 480px; width:60%px;  margin: auto;" class="m-2 border-2 rounded-md shadow-xl">
    </div>
    <br><br>
    <div>
        <p id="lat"></p>
        <p id="long"></p>
    </div>
</div>
{% endblock base %}

templates/ParkingBD/cancelBooking.html
{% extends 'ParkingBD/base.html' %}
{% block title %}
Cancel Booking
{% endblock title %}
{% block base %}
<center>
    <p class="text-xl font-semibold m-4">
        Cancel Booking:
    </p>
</center>
{% if user.is_authenticated %}


<center>
<form method="post" class="border-4 p-4 m-4 rounded-xl shadow-lg w-10/12 max-w-[22rem]">
   {% csrf_token %}
  
    <label class="text-2xl" for="id_status">Are you sure you want to cancel this request?</label>
    
    <p><input hidden="true" class="form-control" id="id_status" name="status" required="" type="number" value="4"></p>
    <br>
    <input class="btn btn-danger" type="submit" value="Cancel Booking">
    </form>
</center>
{% else %}
{% include 'ParkingBD/loginRequest.html'%}
{% endif %}

{% endblock base %}

templates/ParkingBD/customerReview.html
{% extends "base.html" %}
{% block title %}leave a review{% endblock title %}
{% block base %}

{% if user.is_authenticated %}
<div class="m-auto border-4 rounded-xl p-4 sm:w-8/12 xl:w-6/12 2xl:w-6/12  md:w-6/12">
    <img class="w-full h-64 object-cover object-center" src="{{slot.photo.url}}" alt="Sunset in the mountains">
    <div class="font-bold text-xl mb-2">{{slot.garage_name}}</div>
    <p class="font-semibold">Location:</p>
    <p>{{slot.location}}, {{slot.locality}}, {{slot.locality.division}} </p>
    <br>
    <br>
    <div class="form-group">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <p>
                    <select hidden="true" id="id_garage" name="garage" required="">
                        <option selected="" value="{{slot.id}}"></option>
                    </select>
                </p>
                <p>
                    <select hidden="true" id="id_customer" name="customer" required="">
                        <option selected="" value="{{user.id}}"></option>
                    </select>
                </p>
                <p>
                    <label class="font-semibold" for="id_review">Review:</label><br>
                    <input class="border-2 rounded-md w-full h-24" id="id_review" maxlength="500" name="review" type="text">
            </p>
            <br>
            <p>
            <label class="font-semibold" for="id_rating">Rating:</label>
            <br>
<div class="text-sm">     
            <label>
                <input   type="radio" name="rating" value="1">  <i class="fa fa-sm fa-star" aria-hidden="true"></i>
            </label>
            <br>
            <label>
                <input  type="radio" name="rating" value="2"> <i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i>
            </label>
            <br>
            <label>
                <input   type="radio" name="rating" value="3"> <i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i>
            </label>
            <br>
            <label>
                <input   type="radio" name="rating" value="4"> <i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i>
            </label>
            <br>
            <label>
                <input   type="radio" name="rating" value="5"> <i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i><i class="fa fa-sm fa-star" aria-hidden="true"></i>
            </label>
        </div>
            </p>
            </div>
<input  class="text-blue-500 text-center font-semibold p-2 m-2 shadow-md border-2 rounded-md hover:bg-blue-500 hover:text-white duration-200 cursor-pointer" type="submit" value="submit" >
        </form>
    </div>
</div>
    {% else %}
    {% include 'ParkingBD/loginRequest.html'%}
    {% endif %}
{% endblock base %}

templates/ParkingBD/deleteSlot.html
{% extends 'ParkingBD/base.html' %}
{% block title %}
Slot Delete
{% endblock title %}
{% block base %}
<center>
    <p class="text-xl font-semibold m-4">
        Delete Slot:
    </p>
</center>
{% if user.is_authenticated %}


{% if slot.owner.id == user.id %}

<form method="post">
    {% csrf_token %}
    <div class="m-auto text-red-500 font-semibold rouded-xl border-4 shadow-lg text-center w-10/12 max-w-[20rem] p-4">
        <p>Are you sure you want Delete this Slot post?</p>
        <br>
        <p>All the data related to this post would be deleted!</p> 
        <br>
        <input class="text-white font-semi-bold p-1 m-2 px-3 rounded-md m-auto bg-red-500" type="submit" value="Delete">
        <br>
    </div>
</form>
{% else %}
<center>
    <p class='text-red-500'>This page doesn't belong to you</p>
</center>
{% endif %}
{% else %}
{% include 'ParkingBD/loginRequest.html'%}
{% endif %}
{% endblock base %}

templates/ParkingBD/editSlot.html
{% extends 'ParkingBD/base.html' %}
{% block title %}
Edit Slot
{% endblock title %}
{% load widget_tweaks %}
{% block base %}

<center>
    <p class="text-xl font-semibold">
        Edit Slot:
    </p>
</center>

{% if user.is_authenticated %}



<!-- js for long, lat, dropdown, datepicker, checkbox, owner, booking needs to fixed -->


{% if slot.owner.id == user.id %}
<div class="m-auto font-semibold rounded-xl border-4 shadow-lg p-4 m-auto w-10/12 max-w-24">
    <label class="text-lg font-semibold" for="{{ field.id_for_label }}">Location:</label>
    <p>{{slot.location}}, {{slot.locality}}, {{slot.locality.division}}</p>
    <br>
    <form method="post">
        {% csrf_token %}

        <div class="grid xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-2 2xl:grid-cols-2  gap-6">
    <div>
        <label class="text-lg font-semibold" for="id_garage_name">Garage name</label>
        <p><input class="form-control" id="id_garage_name" maxlength="100" name="garage_name" required="" type="text" value="habijabi"></p>
        <label class="text-lg font-semibold" for="id_phone_number">Phone number</label>
        <p><input class="form-control" id="id_phone_number" maxlength="15" name="phone_number" required="" type="text" value="+8801771381929"></p>
        <label class="text-lg font-semibold" for="id_other_number">Other number</label>
        <p><input class="form-control" id="id_other_number" maxlength="15" name="other_number" type="text"></p>
        <label class="text-lg font-semibold" for="id_description">Description</label>
        <p><input class="form-control" id="id_description" maxlength="500" name="description" required="" type="text" value="No description"></p>
        <label class="text-lg font-semibold" for="id_photo">Photo</label>
        <p>Currently: <a href="/media/garage_photos/images_TxjiUQk.jpg">garage_photos/images_TxjiUQk.jpg</a><br>
        Change:
        <input accept="image/*" class="form-control" id="id_photo" name="photo" type="file"></p>
        <label class="text-lg font-semibold" for="id_place_category">Place category</label>
        <p><select class="form-control" id="id_place_category" name="place_category">
        <option selected="" value="Commercial">Commercial</option>
        <option value="Residential">Residential</option>
        </select></p>
        <label class="text-lg font-semibold" for="id_bike_slot">Bike slot</label>
        <p><input class="form-control" id="id_bike_slot" name="bike_slot" required="" type="number" min="0" value="2"></p>
        <label class="text-lg font-semibold" for="id_car_slot">Car slot</label>
        <p><input class="form-control" id="id_car_slot" name="car_slot" required="" type="number" min="0" value="2"></p>
        <label class="text-lg font-semibold" for="id_bicycle_slot">Bicycle slot</label>
        <p><input class="form-control" id="id_bicycle_slot" name="bicycle_slot" required="" type="number" min="0" value="1"></p>

        
</div>
<div>

        <label class="text-lg font-semibold" for="id_allow_monthly">Allow monthly</label>
        <p><input checked="" class="px-2" id="id_allow_monthly" name="allow_monthly" type="checkbox"></p>
        <label class="text-lg font-semibold" for="id_monthly_cost">Monthly cost</label>
        <p><input class="form-control" id="id_monthly_cost" name="monthly_cost" required="" step="any" type="number" min="0" value="7000.0"></p>


        <label class="text-lg font-semibold" for="id_allow_hourly">Allow hourly</label>
        <p><input checked="" class="px-2" id="id_allow_hourly" name="allow_hourly" type="checkbox"></p>
        <label class="text-lg font-semibold" for="id_hourly_cost">Hourly cost</label>
        <p><input class="form-control" id="id_hourly_cost" name="hourly_cost" required="" step="any" type="number" min="0" value="70.0"></p>
        <label class="text-lg font-semibold" for="id_allow_daily">Allow daily</label>
        <p><input checked="" class="px-2" id="id_allow_daily" name="allow_daily" type="checkbox"></p>
        <label class="text-lg font-semibold" for="id_daily_cost">Daily cost</label>
        <p><input class="form-control" id="id_daily_cost" name="daily_cost" required="" step="any" type="number" min="0" value="700.0"></p>
        <label class="text-lg font-semibold" for="id_opening_time">Opening time</label>
        <p><input class="form-control" id="id_opening_time" name="opening_time" required="" type="text" value="23:13:00"></p>
        <label class="text-lg font-semibold" for="id_close_time">Close time</label>
        <p><input class="form-control" id="id_close_time" name="close_time" required="" type="text" value="15:11:00"></p>
        <label class="text-lg font-semibold" for="id_CCTV">CCTV</label>
        <input checked="" class="px-2" id="id_CCTV" name="CCTV" type="checkbox"><br>
        <label class="text-lg font-semibold" for="id_Gaurd">Gaurd</label>
        <input checked="" class="px-2" id="id_Gaurd" name="Gaurd" type="checkbox"><br>
        <label class="text-lg font-semibold" for="id_Indoor">Indoor</label>
        <input checked="" class="px-2" id="id_Indoor" name="Indoor" type="checkbox"><br>
        <br>
        <input class="text-white font-semi-bold p-1 m-2 px-3 rounded-md m-auto bg-blue-500" type="submit" value="Update">
        
        </div>
    </div>
        </form>
</div>
    {% else %}
    <center>
        <p class='text-red-500'>This page doesn't belong to you</p>
    </center>

    {% endif %}
{% else %}
{% include 'ParkingBD/loginRequest.html'%}
{% endif %}
{% endblock base %}

templates/ParkingBD/loginRequest.html
<div class="card" style="width: 18rem; margin:auto">
    <div class="card-body">
        <h5 class="card-title">You are not Signed in!</h5>
        <p class="card-text">
            please Sign in or Register to continue.
        </p>
        <br>
        <hr>
        <br>
        <a href="{% url 'login' %}" class="btn btn-primary">Sign in</a>
    </div>
</div>

templates/ParkingBD/rejectBooking.html
{% extends 'ParkingBD/base.html' %}
{% block title %}
Reject Booking
{% endblock title %}
{% block base %}
{% if user.is_authenticated %}

<center>
    <p class="text-xl font-semibold m-4">
        Reject Booking:
    </p>
</center>

<center>
<form method="post" class="border-4 p-4 m-4 rounded-xl shadow-lg w-10/12 max-w-[22rem]">
   {% csrf_token %}
  
    <label class="text-2xl" for="id_status">Are you sure you want to reject this request?</label>
    <p>Customer would be notified that you have rejected this request.</p>
    
    <p><input hidden="true" class="form-control" id="id_status" name="status" required="" type="number" value="2"></p>
    <br>
    <input class="btn btn-danger" type="submit" value="Reject">
    </form>
</center>
{% else %}
{% include 'ParkingBD/loginRequest.html'%}
{% endif %}

{% endblock base %}

templates/ParkingBD/slotbooking.html
{% extends 'ParkingBD/base.html' %}
{%load crispy_forms_tags %}

{% block title %}
Booking Form
{% endblock title %}
{% block base %}

<center>
    <p class="text-xl font-semibold m-4">
        Booking form:
    </p>
</center>
{% if user.is_authenticated %}


{% if user.is_authenticated %}

<div class="m-auto rounded-xl border-4 shadow-lg p-4 m-auto w-10/12 max-w-24">
    <p class="text-center text-xl">Slot Name: {{slot.garage_name}}</p>
<br><br>

    <form method="post">
        {% csrf_token %}
<div class="grid xl:grid-cols-2 lg:grid-cols-2 md:grid-cols-2 2xl:grid-cols-2  gap-6">
    <div>
        <div class="form-group" id="div_id_garage"> <label class="requiredField" for="id_garage">
                Garage Name<span class="asteriskField">*</span> </label>
            <div> <select class="select form-control" id="id_garage" name="garage" required="">
                    <option value="{{slot.id}}">{{slot.garage_name}}</option>
                </select> </div>
        </div>
        <div class="form-group" id="div_id_owner"> <label class="requiredField" for="id_owner">
                Owner<span class="asteriskField">*</span> </label>
            <div> <select class="select form-control" id="id_owner" name="owner" required="">
                    <option value="{{slot.owner.id}}">{{slot.owner.username}}</option>
                </select> </div>
        </div>
        <div class="form-group" id="div_id_customer"> <label class="requiredField" for="id_customer">
                Customer<span class="asteriskField">*</span> </label>
            <div> <select class="select form-control" id="id_customer" name="customer" required="">
                    <option value="{{user.id}}">{{user.username}}</option>
                </select> </div>
        </div>
        <div class="form-group" id="div_id_customer_address"> <label class="requiredField" for="id_customer_address">
                Customer address<span class="asteriskField">*</span> </label>
            <div> <input class="textinput textInput form-control" id="id_customer_address" maxlength="100"
                    name="customer_address" required="" type="text"> </div>
        </div>
        <div class="form-group" id="div_id_phone_number"> <label class="requiredField" for="id_phone_number">
                Phone number<span class="asteriskField">*</span> </label>
            <div> {% if user.profile.phone %}
                <input id="id_phone_number" maxlength="20" name="phone_number" required="" type="text"
                    value="{{user.profile.phone}}">
                {% else %}
                <input id="id_phone_number" maxlength="20" name="phone_number" required="" type="text"
                    placeholder="Must fill this field">
                {% endif %}
            </div>
        </div>
        <div class="form-group" id="div_id_vehice_number"> <label class="requiredField" for="id_vehice_number">
                Vehice number<span class="asteriskField">*</span> </label>
            <div> <input class="textinput textInput form-control" id="id_vehice_number" maxlength="50"
                    name="vehice_number" required="" type="text"> </div>
        </div>
        <div class="form-group" id="div_id_vehicle_type"> <label class="requiredField" for="id_vehicle_type">
                Vehicle type<span class="asteriskField">*</span> </label>
            <div> <select class="select form-control" id="id_vehicle_type" name="vehicle_type">
                    {% if slot.bike_slot > 0 %}
                    <option value="Bike">Bike</option>
                    {% endif %}
                    {% if slot.car_slot > 0 %}
                    <option selected="" value="Car">Car</option>
                    {% endif %}
                    {% if slot.bicycle_slot > 0 %}
                    <option value="Bicycle">Bicycle</option>
                    {% endif %}
                </select> </div>
        </div>
</div>
<div>


        <div class="form-group" id="div_id_image_of_necesssary_papers"> <label class=""
                for="id_image_of_necesssary_papers">
                Image of necesssary papers(Optional)
            </label>
            <div> <input accept="image/*" class="clearablefileinput form-control-file"
                    id="id_image_of_necesssary_papers" name="image_of_necesssary_papers" type="file"> </div>
        </div>
        <div class="form-group" id="div_id_type_of_booking"> <label class="requiredField" for="id_type_of_booking">
                Type of booking<span class="asteriskField">*</span> </label>
            <div>
                <div class="text-sm">
                    <p>[ Rate:</p>
                    {% if slot.allow_hourly == True %}
                    <p>{{slot.hourly_cost}} Tk./hour</p>
                    {% endif %}
                    {% if slot.allow_daily == True %}
                    <p>{{slot.daily_cost}} Tk./day</p>
                    {% endif %}
                    {% if slot.allow_monthly == True %}
                    <p>{{slot.monthly_cost}} Tk./month</p>
                    {% endif %}]

                </div>
                <select class="select form-control" id="id_type_of_booking" name="type_of_booking">
                    <option selected="" value="Hour">Hour</option>
                    <option value="Day">Day</option>
                    <option value="Month">Month</option>
                </select>
            </div>
        </div>

        <div class="form-group" id="div_id_booking_quantity"> <label class="requiredField" for="id_booking_quantity">
                Booking quantity<span class="asteriskField">*</span> </label>
            <div> <input class="numberinput form-control" id="id_booking_quantity" name="booking_quantity" required=""
                    type="number" min="0" value="1"> </div>
        </div>
        <div class="form-group" id="div_id_start_time"> <label class="requiredField" for="id_start_time">
                Start time<span class="asteriskField">*</span> </label>
            <div> <input class="textinput textInput form-control" id="id_start_time" maxlength="25" name="start_time"
                    required="" type="time"> </div>
        </div>
        <div class="form-group" id="div_id_start_date"> <label class="requiredField" for="id_start_date">
                Start date<span class="asteriskField">*</span> </label>
            <div> <input class="textinput textInput form-control" id="id_start_date" maxlength="25" name="start_date"
                    required="" type="date"> </div>
        </div>

        <input class="btn btn-info bg-info" type="submit"
            value="submit">


        </div>
    </div>
    </form>


</div>
{% else %}

{% include 'ParkingBD/loginRequest.html' %}

{% endif %}
{% else %}
{% include 'ParkingBD/loginRequest.html'%}
{% endif %}
{% endblock base %}

templates/ParkingBD/testForm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
testForm
{% endblock title %}
{% block base %}
<form>
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit">
</form>
{% endblock base %}